// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trending.proto

// Protobuf Java Version: 3.25.3
package com.trendingmoviesservice.grpc;

public interface TopTrendingMoviesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trending.TopTrendingMoviesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .trending.TrendingMovie movies = 1;</code>
   */
  java.util.List<com.trendingmoviesservice.grpc.TrendingMovie> 
      getMoviesList();
  /**
   * <code>repeated .trending.TrendingMovie movies = 1;</code>
   */
  com.trendingmoviesservice.grpc.TrendingMovie getMovies(int index);
  /**
   * <code>repeated .trending.TrendingMovie movies = 1;</code>
   */
  int getMoviesCount();
  /**
   * <code>repeated .trending.TrendingMovie movies = 1;</code>
   */
  java.util.List<? extends com.trendingmoviesservice.grpc.TrendingMovieOrBuilder> 
      getMoviesOrBuilderList();
  /**
   * <code>repeated .trending.TrendingMovie movies = 1;</code>
   */
  com.trendingmoviesservice.grpc.TrendingMovieOrBuilder getMoviesOrBuilder(
      int index);
}
