// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trending.proto

// Protobuf Java Version: 3.25.3
package com.trendingmoviesservice.grpc;

public interface TopTrendingMoviesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trending.TopTrendingMoviesRequest)
    com.google.protobuf.MessageOrBuilder {
}
