// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trending.proto

// Protobuf Java Version: 3.25.3
package com.trendingmoviesservice.grpc;

public final class TrendingProto {
  private TrendingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trending_TopTrendingMoviesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trending_TopTrendingMoviesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trending_TrendingMovie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trending_TrendingMovie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trending_TopTrendingMoviesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trending_TopTrendingMoviesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016trending.proto\022\010trending\"\032\n\030TopTrendin" +
      "gMoviesRequest\"9\n\rTrendingMovie\022\020\n\010movie" +
      "_id\030\001 \001(\t\022\026\n\016average_rating\030\002 \001(\001\"D\n\031Top" +
      "TrendingMoviesResponse\022\'\n\006movies\030\001 \003(\0132\027" +
      ".trending.TrendingMovie2r\n\017TrendingServi" +
      "ce\022_\n\024GetTopTrendingMovies\022\".trending.To" +
      "pTrendingMoviesRequest\032#.trending.TopTre" +
      "ndingMoviesResponseB1\n\036com.trendingmovie" +
      "sservice.grpcB\rTrendingProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_trending_TopTrendingMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trending_TopTrendingMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trending_TopTrendingMoviesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_trending_TrendingMovie_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trending_TrendingMovie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trending_TrendingMovie_descriptor,
        new java.lang.String[] { "MovieId", "AverageRating", });
    internal_static_trending_TopTrendingMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trending_TopTrendingMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trending_TopTrendingMoviesResponse_descriptor,
        new java.lang.String[] { "Movies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
