// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trending.proto

// Protobuf Java Version: 3.25.3
package com.trendingmoviesservice.grpc;

public interface TrendingMovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trending.TrendingMovie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string movie_id = 1;</code>
   * @return The movieId.
   */
  java.lang.String getMovieId();
  /**
   * <code>string movie_id = 1;</code>
   * @return The bytes for movieId.
   */
  com.google.protobuf.ByteString
      getMovieIdBytes();

  /**
   * <code>double average_rating = 2;</code>
   * @return The averageRating.
   */
  double getAverageRating();
}
