// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trending.proto

// Protobuf Java Version: 3.25.3
package com.trendingmoviesservice.grpc;

/**
 * Protobuf type {@code trending.TrendingMovie}
 */
public final class TrendingMovie extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trending.TrendingMovie)
    TrendingMovieOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrendingMovie.newBuilder() to construct.
  private TrendingMovie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrendingMovie() {
    movieId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrendingMovie();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trendingmoviesservice.grpc.TrendingProto.internal_static_trending_TrendingMovie_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trendingmoviesservice.grpc.TrendingProto.internal_static_trending_TrendingMovie_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trendingmoviesservice.grpc.TrendingMovie.class, com.trendingmoviesservice.grpc.TrendingMovie.Builder.class);
  }

  public static final int MOVIE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object movieId_ = "";
  /**
   * <code>string movie_id = 1;</code>
   * @return The movieId.
   */
  @java.lang.Override
  public java.lang.String getMovieId() {
    java.lang.Object ref = movieId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      movieId_ = s;
      return s;
    }
  }
  /**
   * <code>string movie_id = 1;</code>
   * @return The bytes for movieId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMovieIdBytes() {
    java.lang.Object ref = movieId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      movieId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVERAGE_RATING_FIELD_NUMBER = 2;
  private double averageRating_ = 0D;
  /**
   * <code>double average_rating = 2;</code>
   * @return The averageRating.
   */
  @java.lang.Override
  public double getAverageRating() {
    return averageRating_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(movieId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movieId_);
    }
    if (java.lang.Double.doubleToRawLongBits(averageRating_) != 0) {
      output.writeDouble(2, averageRating_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(movieId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, movieId_);
    }
    if (java.lang.Double.doubleToRawLongBits(averageRating_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, averageRating_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trendingmoviesservice.grpc.TrendingMovie)) {
      return super.equals(obj);
    }
    com.trendingmoviesservice.grpc.TrendingMovie other = (com.trendingmoviesservice.grpc.TrendingMovie) obj;

    if (!getMovieId()
        .equals(other.getMovieId())) return false;
    if (java.lang.Double.doubleToLongBits(getAverageRating())
        != java.lang.Double.doubleToLongBits(
            other.getAverageRating())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MOVIE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMovieId().hashCode();
    hash = (37 * hash) + AVERAGE_RATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAverageRating()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.trendingmoviesservice.grpc.TrendingMovie parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.trendingmoviesservice.grpc.TrendingMovie parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trendingmoviesservice.grpc.TrendingMovie parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trendingmoviesservice.grpc.TrendingMovie prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trending.TrendingMovie}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trending.TrendingMovie)
      com.trendingmoviesservice.grpc.TrendingMovieOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trendingmoviesservice.grpc.TrendingProto.internal_static_trending_TrendingMovie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trendingmoviesservice.grpc.TrendingProto.internal_static_trending_TrendingMovie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trendingmoviesservice.grpc.TrendingMovie.class, com.trendingmoviesservice.grpc.TrendingMovie.Builder.class);
    }

    // Construct using com.trendingmoviesservice.grpc.TrendingMovie.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      movieId_ = "";
      averageRating_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trendingmoviesservice.grpc.TrendingProto.internal_static_trending_TrendingMovie_descriptor;
    }

    @java.lang.Override
    public com.trendingmoviesservice.grpc.TrendingMovie getDefaultInstanceForType() {
      return com.trendingmoviesservice.grpc.TrendingMovie.getDefaultInstance();
    }

    @java.lang.Override
    public com.trendingmoviesservice.grpc.TrendingMovie build() {
      com.trendingmoviesservice.grpc.TrendingMovie result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trendingmoviesservice.grpc.TrendingMovie buildPartial() {
      com.trendingmoviesservice.grpc.TrendingMovie result = new com.trendingmoviesservice.grpc.TrendingMovie(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.trendingmoviesservice.grpc.TrendingMovie result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.movieId_ = movieId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.averageRating_ = averageRating_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trendingmoviesservice.grpc.TrendingMovie) {
        return mergeFrom((com.trendingmoviesservice.grpc.TrendingMovie)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trendingmoviesservice.grpc.TrendingMovie other) {
      if (other == com.trendingmoviesservice.grpc.TrendingMovie.getDefaultInstance()) return this;
      if (!other.getMovieId().isEmpty()) {
        movieId_ = other.movieId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAverageRating() != 0D) {
        setAverageRating(other.getAverageRating());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              movieId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              averageRating_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object movieId_ = "";
    /**
     * <code>string movie_id = 1;</code>
     * @return The movieId.
     */
    public java.lang.String getMovieId() {
      java.lang.Object ref = movieId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string movie_id = 1;</code>
     * @return The bytes for movieId.
     */
    public com.google.protobuf.ByteString
        getMovieIdBytes() {
      java.lang.Object ref = movieId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string movie_id = 1;</code>
     * @param value The movieId to set.
     * @return This builder for chaining.
     */
    public Builder setMovieId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      movieId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string movie_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMovieId() {
      movieId_ = getDefaultInstance().getMovieId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string movie_id = 1;</code>
     * @param value The bytes for movieId to set.
     * @return This builder for chaining.
     */
    public Builder setMovieIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      movieId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double averageRating_ ;
    /**
     * <code>double average_rating = 2;</code>
     * @return The averageRating.
     */
    @java.lang.Override
    public double getAverageRating() {
      return averageRating_;
    }
    /**
     * <code>double average_rating = 2;</code>
     * @param value The averageRating to set.
     * @return This builder for chaining.
     */
    public Builder setAverageRating(double value) {

      averageRating_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double average_rating = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAverageRating() {
      bitField0_ = (bitField0_ & ~0x00000002);
      averageRating_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trending.TrendingMovie)
  }

  // @@protoc_insertion_point(class_scope:trending.TrendingMovie)
  private static final com.trendingmoviesservice.grpc.TrendingMovie DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trendingmoviesservice.grpc.TrendingMovie();
  }

  public static com.trendingmoviesservice.grpc.TrendingMovie getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrendingMovie>
      PARSER = new com.google.protobuf.AbstractParser<TrendingMovie>() {
    @java.lang.Override
    public TrendingMovie parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TrendingMovie> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrendingMovie> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trendingmoviesservice.grpc.TrendingMovie getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

